### ISSUE TITLE
[DISCUSS] Which flavo(u)rs of English do we use?

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/tech-writing-guidelines#36]
## Background

In a cross-docs meeting, someone brought up a concern about restricting the new docs content linter to only accept American English since we have historically allowed both American and British English. 

The current guidelines across internal documentation are unclear:

* "Yes, our docs are 99.999% in English. And American English at that." ([Writing for an international audience](https://github.com/elastic/tech-writing-guidelines/blob/main/docs/writing-tips.mdx#writing-for-an-international-audience))
* "We default to American English (realize) rather than British English (realise). However, in content geared towards a specific region, we will default to the spelling used in that region." (Brand guidelines)
* "Our products and documentation are mostly exclusively written in US (sometimes UK) English." (proposed in [elastic/tech-writing-guidelines#35](https://github.com/elastic/tech-writing-guidelines/pull/35/commits/652530c9a55fbc7d9bbca4166959939ad67b8e25#diff-7e5ec73dde4d9d58ea0fe30ec58683a3b6323676dea46839aac6c26c965c0220R19))

## Proposal

⚠️  Edit: Updated proposals in https://github.com/elastic/tech-writing-guidelines/issues/36#issuecomment-1145319345. 

We should make the guidance clearer using some variation of one of the following:

* We allow both American and British English in all technical documentation. When referring to a product, feature, or UI element match the flavo(u)r of English it uses.
* We use American English unless referring to a product, feature, or UI element that uses a different flavor of English.

## Discussion

Should we enforce American English spelling or allow both American and British English?

**Pros of allowing only American English:** 
* **[user experience]** Consistent language may be better for global audiences (ref: [Google developer documentation style guide](https://developers.google.com/style/translation#be-consistent)).
* **[maintenance]** If we want to translate our docs in the future, consistent language can make the process more efficient.
* **[maintenance]** If we want to spell check our docs, the [open source `retext-spell` plugin](https://github.com/retextjs/retext-spell) will work without customization.
    * The open source spelling plugin does not support two dictionaries. To support both variations we'll have to create a custom spelling plugin that accepts two dictionaries or create a custom dictionary that merges [American](https://github.com/wooorm/dictionaries/tree/main/dictionaries/en) and [British](https://github.com/wooorm/dictionaries/tree/main/dictionaries/en-GB) terms. Either way, this system will have to be maintained.
* _What am I missing?_

**Pros of allowing both:** 
* **[contributor experience]** Engineers and technical writers are used to writing both ways.
* **[perception]** It reflects that we speak different flavo(u)rs of English as a team. Writing docs is a collective, global effort.
* _What am I missing?_

@elastic/docs please share your opinion below!

## Next steps

I will hold on exploring a custom spelling plugin until we make a decision, but early research suggests it is possible!

**Comment by dedemorton** [comment]
I realize that we are talking about documentation here, but I think that allowing all flavors of English has resulted in APIs  and code names that use a mix of British and American English. IMO...that's a bug not a feature because it puts the burden on users to remember which flavor of English we decided to use for a specific API or function name.  To remove ambiguity, I think it's better to use one dictionary. American English is the defacto standard for most documentation, so I would go with that.

**Comment by lcawl** [comment]
I agree that it's a good idea to strive for consistency on a single dictionary going forward, as long as we're okay with the fact that deviations in existing APIs might take a long time to weed out (if ever) due to backwards compatibility. So as long as the linter produces warnings only or can be ignored for those cases (i.e. it's a non-blocking check), it sounds good to me.

**Comment by goodroot** [comment]
IMO:

I do not see American English as a defacto standard.

Why American English over International English?

That is a subjective/imperial argument with no answer.

Therefore I do not support rejecting one and supporting the other.

If rejecting one is a requirement to lint spelling, then I posit we do not lint spelling.

Alternative is that each writer spell checks their own writing.

In saying that, am supportive of linting common spelling of Elastic product names & concepts vs. dictionary spelling.

**Comment by florent-leborgne** [comment]
Thanks for opening this discussion! 
I'm not in favour (or favor?) of one over the other, but paving the way for consistency is important. Our writing guidelines & tips should apply to both docs and product content whenever possible. While I think it may be acceptable to have a mix in different sets of docs, I believe there must be consistency at least within the same set of content. I also believe that we need a clear choice (no mix) for UI content, including APIs, to provide the best UX. 

Quick note: if we end up making different choices for docs and UI, we should make sure both are clearly stated in the guidelines.

**Comment by joepeeples** [comment]
Is it possible to lint English spellings _both ways_? As in, the linter pings on both `color` AND `colour`, with a note saying something like "This term has different spellings based on regional English variations"? 

As @lcawl suggested, if this note is a warning only and can be ignored, then the linter isn't trying to impose one world order over another; it's highlighting some common spots for possible inconsistency but leaving it up to the writer to decide.

**Comment by chriscressman** [comment]
Great discussion so far!

I like proposals that move us closer to operating as a cohesive writing group. If we all use the same tool to check our spelling, we move one step in that direction.

@colleenmcginnis has built the linter on Unified, the same toolchain that Next Docs uses for parsing and serializing. I think this is a good choice. That choice pushes us to standardize on a single dictionary.

I have no opinion on the dictionary we use. As a writer, I suspect it will be trivial to conform to any English dictionary. I haven't yet seen any compelling arguments that the choice of dictionary affects readers.

Additional considerations:

- After choosing a dictionary, we will have existing content that doesn't conform (@lcawl mentioned this). The linter may have an "auto-fix" option, and Colleen already demonstrated several "skip" options, so I'm confident we can work through this one pretty easily. This is therefore not affecting my opinion on dictionary choice.
- Elastic currently advocates for specific spellings for some words and phrases (@goodroot mentioned this). Can these spellings be layered on top of the English dictionary, or must the English and Elastic dictionaries be merged into a custom dictionary? This affects my opinion of whether we should put effort into maintaining a custom dictionary.

**Comment by kellyemurphy** [comment]
It might be a good idea to check in with the folks who are doing/managing translations for other content. Does it make a big difference in cost, effort, or sourcing? I'm always an advocate for future-proofing and I could see it possibly adding extra expense and time if we're not consistent or if we choose the "wrong" type of English. 

Thanks @goodroot for bringing up International English, a third route is always good to consider. A light googling brought a [good blog post up from a translation company](https://blog.acolad.com/different-types-of-english) (in case you're like me and needed to know the difference). It also discusses what markets generally prefer which. Spoiler: It depends.

I'm a fan of choosing one and sticking with it, TBH. It simplifies things across the board and sets a standard. I don't care what we pick, but I'd rather we pick just one. Support for variance is something we hold onto as a value from our old days, but does it really still serve us? Is this important enough that we should open a UX study about it? Or could we do more research around the topic to arrive at a consensus?

**Comment by dedemorton** [comment]
IMO standardizing on _any_ flavor of English likely has roots in colonialism, so I’m not sure how to proceed with that concern. My interest lies solely in writing clear, consistent docs. 

To add some more data points, I did a quick survey of existing style guides starting with the [list published by Write the Docs](https://www.writethedocs.org/guide/writing/style-guides/). 

All the companies below use US English. Most of the other companies in the list sidestep the issue of which dictionary to use by providing word lists (which btw mostly promote US English spellings).  

- Microsoft: https://docs.microsoft.com/en-us/style-guide/word-choice/use-us-spelling-avoid-non-english-words
- SUSE: https://documentation.suse.com/style/current/single-html/docu_styleguide/
- Google: https://developers.google.com/style/spelling
- Ruby on Rails:  https://guides.rubyonrails.org/api_documentation_guidelines.html 

I think word lists might be the best way forward. Then the style guide doesn't have to explicitly state that we use US English, but we can use a single dictionary to check spelling. I think the number of words that matter is actually pretty small.

I just want to avoid ambiguity so that someone sitting at a console someday doesn't have to ask themselves, "Is the command  `add license` or `add licence`?" (totally made up example, but you get the point)

**Comment by colleenmcginnis** [comment]
Thanks for all the discussion so far! Here's my attempt to summarize the discussion so far and suggest some next steps. 😅 

>If rejecting one is a requirement to lint spelling, then I posit we do not lint spelling.

I just wanted to say that the linter 🤖  works for _us_ not the other way around. 🙂  While the ability to lint shouldn't be _the_ reason to choose one approach over another, I do think it acts as _a_ reason for us to make _some_ decision, document it clearly, and commit to it across teams.

For the purposes of this discussion, let's assume we can get the linter to do _anything_ we want so we can really focus in on the experience we want to provide to readers and how we can clearly articulate our approach in the writing guidelines to promote consistency. In my experience, discussing the UX of the linter will be easier once we've agreed on the end goal.

## ⚖️  Considerations

Here are some of the major themes that have come up in the discussion so far (and where we might need to gather more info before making a decision):

* **Industry standards**: We should consider what standard other companies in the industry use.
  * @dedemorton did some research on other companies in the industry.
* **User experience**: We should consider the impact this will have on users. We can understand the user impact through case studies, user stories, interviews with UX experts, or a UX study with real users.
  * @dedemorton considered what the user might be thinking: "Allowing all flavors of English has resulted in APIs and code names that use a mix of British and American English. IMO...that's a bug not a feature because it puts the burden on users to remember which flavor of English we decided to use for a specific API or function name."
  * @florent-leborgne brought up that "our writing guidelines & tips should apply to both docs and product content whenever possible". Are there other stakeholders who should be included in this discussion from the product side?
  * @kellyemurphy asked "Is this important enough that we should open a UX study about it?" This isn't specific to Elastic or our users, but I did find some relevant information from [Nielsen Norman Group](https://www.nngroup.com/). Their usability studies provide two firm insights on American vs. British English for web content: (1) language matters and (2) be consistent. Varying the style confuses everyone, signals poor attention to detail, and might [reduce credibility](https://www.nngroup.com/articles/trust-or-bust-communicating-trustworthiness-in-web-design/). ([source](https://www.nngroup.com/articles/american-vs-british-english-for-web/))
* **Our values**: We should consider if using multiple flavo(u)rs of English continues to be an effective way to demonstrate that writing docs is a collective, global effort. If it is, it might be worth breaking from industry standards.
    * @kellyemurphy said "Support for variance is something we hold onto as a value from our old days, but does it really still serve us?"
* **Future-proofing**: We should consider how this might impact (possible) future initiatives like translating docs.
  * @kellyemurphy do you have names of individuals or teams we could reach out to who work on translation?
* **Backward compatibility / Exceptions**:  We should consider the situations in which we will have to break from the final guidelines we choose. Any systems that are built to enforce guidelines (like the linter) must be able to accommodate these exceptions.
  * @lcawl warns that we'll have to be okay with "deviations in existing APIs might take a long time to weed out (if ever) due to backwards compatibility"
  * @chriscressman reinforces that any systems will need to be able to handle these exceptions: "The linter may have an 'auto-fix' option, and Colleen already demonstrated several 'skip' options, so I'm confident we can work through this one pretty easily. This is therefore not affecting my opinion on dictionary choice."

## 🔢  Potential guidelines

Here's my attempt at capturing the various options I see emerging from this discussion (from least to most restrictive):

* **Option 1**^: We allow both American and British English in all technical documentation.
  * When referring to a product, feature, API, or UI element you must match the flavo(u)r of English it uses.
  * For any other text, you can use either flavo(u)r of English.
* **Option 2**: We allow both American and British English in all technical documentation.
  * Choose and consistently use one flavo(u)r of English for an entire book (or page?).
  * Regardless of which flavor you choose, when referring to a product, feature, API, or UI element match the flavo(u)r of English it uses.
* **Option 3**^^: We use International English unless referring to a product, feature, API, or UI element that uses a different flavor of English.
  * There is no standard definition of what International English includes. At Elastic, our definition of International English is ___.
* **Option 4**: We use British English unless referring to a product, feature, API, or UI element that uses a different flavour of English.
* **Option 5**: We use American English unless referring to a product, feature, API, or UI element that uses a different flavor of English.
* _Am I missing any other options?_

^ This is essentially what we do now (I think...).
^^ This would require us defining what "International English" means at Elastic.

##  📝  Next steps

It sounds like most people who have contributed to the conversation so far are in favor of some level of consistency, but do not have strong opinions about the flavo(u)rs we use. Maybe we can narrow down our options by considering:

* Are there any of the options listed above that you are strongly against?
* Any that you are strongly in favor of?
* Are there alternative options I missed?

**Comment by ollyhowell** [comment]
I personally think US English is the best option - like it or not, it's the standard. Everyone understands it (!) and it's straight-forward to translate. British and International English bring other problems and complexities, and it's better to have one clear standard than none/many. 

I'd be in favour of aligning on this but allowing some time and space for us to get there in terms of existing content i.e. it is not trivial or immediately necessary for us to immediately make all existing content match this standard. I also think it's probably not worth the pain to fix legacy code or API names, and we could just treat these as historical exceptions (while being clear with developers etc. for future code or API element naming.

**Comment by leemthompo** [comment]
Great discussion. I think we've touched on every importance nuance here, not much to add! This is the kind of complex decision that might require a referendum. 🙂

**Comment by colleenmcginnis** [comment]
Thanks for all the discussion here! I've drafted proposed guidelines to be added to the [Writing tips](https://github.com/elastic/tech-writing-guidelines/blob/main/docs/writing-tips.mdx) guide. The proposal uses **Option 5** from above. This option:

✔ Promotes consistency to reduce uncertainty among both readers and contributors.
✔ Is aligned with industry standards.
✔ Is aligned with Elastic brand standards.
✔ Allows us the flexibility to account for products, features, and APIs that use other variations of English.

The biggest downside of this option (based on the discussion) seems to be that it's a departure from our approach in Elastic's early days. However, I'm excited to continue discussing how we can keep demonstrating that writing docs is a collective, global effort through other strategies like using examples that reflect our global team and user base, further restricting regionalisms and idioms, and encouraging plain language!

See the proposed guidelines in https://github.com/elastic/tech-writing-guidelines/pull/43. I will follow up with a separate PR to make updates to the linter to account for the exceptions discussed above.

If we want to revisit this decision in the future, I do think **Option 2** and **Option 3** are also possible solutions, but would  require the group to make additional decisions (for Option 2 we'd need to decide if we want consistency by book or page and for Option 3 we'd need to decide on a definition of International English).

**Comment by colleenmcginnis** [comment]
Here are the next steps I'm tracking:

- [ ] @colleenmcginnis Finalize and publish updates to the Writing tips guide (https://github.com/elastic/tech-writing-guidelines/pull/43)
- [ ] @florent-leborgne Integrate new guidelines into the new Inclusivity guidelines (https://github.com/elastic/tech-writing-guidelines/pull/35)
- [ ] @colleenmcginnis Update linter to account for exceptions discussed here (TBD)
